export const collections = [
  {
    id: "GeoJson",
    displayName: "GeoJson",
    displayField: "id",
    capabilities: {
      dataOperations: [
        "PATCH",
        "IS_REFERENCED",
        "INSERT",
        "SAVE",
        "BULK_INSERT",
        "BULK_UPDATE",
        "UPDATE",
        "TRUNCATE",
        "REMOVE",
        "REMOVE_REFERENCE",
        "COUNT",
        "BULK_PATCH",
        "FIND",
        "REPLACE_REFERENCES",
        "BULK_REMOVE",
        "INSERT_REFERENCE",
        "GET",
        "BULK_SAVE",
        "QUERY_REFERENCED",
        "DISTINCT",
        "AGGREGATE",
      ],
      collectionOperations: ["UPDATE", "REMOVE"],
      indexLimits: {
        regular: 3,
        unique: 1,
        total: 4,
      },
    },
    fields: [
      {
        key: "id",
        displayName: "id",
        type: "TEXT",
        systemField: false,
        capabilities: {
          sortable: true,
          queryOperators: [
            "EQ",
            "LT",
            "GT",
            "NE",
            "LTE",
            "GTE",
            "STARTS_WITH",
            "ENDS_WITH",
            "CONTAINS",
            "HAS_SOME",
            "HAS_ALL",
            "EXISTS",
            "URLIZED",
          ],
        },
        encrypted: false,
        plugins: [],
      },
      {
        key: "geoJson",
        displayName: "geoJson",
        type: "OBJECT",
        systemField: false,
        capabilities: {
          sortable: true,
          queryOperators: [
            "EQ",
            "LT",
            "GT",
            "NE",
            "LTE",
            "GTE",
            "STARTS_WITH",
            "ENDS_WITH",
            "CONTAINS",
            "HAS_SOME",
            "HAS_ALL",
            "EXISTS",
            "URLIZED",
          ],
        },
        encrypted: false,
        plugins: [],
      },
    ],
    permissions: {
      insert: "ADMIN",
      update: "ADMIN",
      remove: "ADMIN",
      read: "ANYONE",
    },
    plugins: [
      {
        type: "EDITABLE_PAGE_LINK",
        editablePageLinkOptions: {
          isPersisted: true,
          isMutable: false,
        },
      },
    ],
  },
  {
    id: "Icons",
    displayName: "Icons",
    displayField: "id",
    capabilities: {
      dataOperations: [
        "PATCH",
        "IS_REFERENCED",
        "INSERT",
        "SAVE",
        "BULK_INSERT",
        "BULK_UPDATE",
        "UPDATE",
        "TRUNCATE",
        "REMOVE",
        "REMOVE_REFERENCE",
        "COUNT",
        "BULK_PATCH",
        "FIND",
        "REPLACE_REFERENCES",
        "BULK_REMOVE",
        "INSERT_REFERENCE",
        "GET",
        "BULK_SAVE",
        "QUERY_REFERENCED",
        "DISTINCT",
        "AGGREGATE",
      ],
      collectionOperations: ["UPDATE", "REMOVE"],
      indexLimits: {
        regular: 3,
        unique: 1,
        total: 4,
      },
    },
    fields: [
      {
        key: "id",
        displayName: "id",
        type: "TEXT",
        systemField: false,
        capabilities: {
          sortable: true,
          queryOperators: [
            "EQ",
            "LT",
            "GT",
            "NE",
            "LTE",
            "GTE",
            "STARTS_WITH",
            "ENDS_WITH",
            "CONTAINS",
            "HAS_SOME",
            "HAS_ALL",
            "EXISTS",
            "URLIZED",
          ],
        },
        encrypted: false,
        plugins: [],
      },
      {
        key: "image",
        displayName: "image",
        type: "IMAGE",
        systemField: false,
        capabilities: {
          sortable: true,
          queryOperators: [
            "EQ",
            "LT",
            "GT",
            "NE",
            "LTE",
            "GTE",
            "STARTS_WITH",
            "ENDS_WITH",
            "CONTAINS",
            "HAS_SOME",
            "HAS_ALL",
            "EXISTS",
            "URLIZED",
          ],
        },
        encrypted: false,
        plugins: [],
      },
    ],
    permissions: {
      insert: "ADMIN",
      update: "ADMIN",
      remove: "ADMIN",
      read: "ANYONE",
    },
    plugins: [
      {
        type: "EDITABLE_PAGE_LINK",
        editablePageLinkOptions: {
          isPersisted: true,
          isMutable: false,
        },
      },
    ],
  },
  {
    id: "Points",
    displayName: "Points",
    displayField: "id",
    capabilities: {
      dataOperations: [
        "PATCH",
        "IS_REFERENCED",
        "INSERT",
        "SAVE",
        "BULK_INSERT",
        "BULK_UPDATE",
        "UPDATE",
        "TRUNCATE",
        "REMOVE",
        "REMOVE_REFERENCE",
        "COUNT",
        "BULK_PATCH",
        "FIND",
        "REPLACE_REFERENCES",
        "BULK_REMOVE",
        "INSERT_REFERENCE",
        "GET",
        "BULK_SAVE",
        "QUERY_REFERENCED",
        "DISTINCT",
        "AGGREGATE",
      ],
      collectionOperations: ["UPDATE", "REMOVE"],
      indexLimits: {
        regular: 3,
        unique: 1,
        total: 4,
      },
    },
    fields: [
      {
        key: "id",
        displayName: "id",
        type: "TEXT",
        systemField: false,
        capabilities: {
          sortable: true,
          queryOperators: [
            "EQ",
            "LT",
            "GT",
            "NE",
            "LTE",
            "GTE",
            "STARTS_WITH",
            "ENDS_WITH",
            "CONTAINS",
            "HAS_SOME",
            "HAS_ALL",
            "EXISTS",
            "URLIZED",
          ],
        },
        encrypted: false,
        plugins: [],
      },
      {
        key: "lat",
        displayName: "lat",
        type: "NUMBER",
        systemField: false,
        capabilities: {
          sortable: true,
          queryOperators: [
            "EQ",
            "LT",
            "GT",
            "NE",
            "LTE",
            "GTE",
            "STARTS_WITH",
            "ENDS_WITH",
            "CONTAINS",
            "HAS_SOME",
            "HAS_ALL",
            "EXISTS",
            "URLIZED",
          ],
        },
        encrypted: false,
        plugins: [],
      },
      {
        key: "long",
        displayName: "long",
        type: "NUMBER",
        systemField: false,
        capabilities: {
          sortable: true,
          queryOperators: [
            "EQ",
            "LT",
            "GT",
            "NE",
            "LTE",
            "GTE",
            "STARTS_WITH",
            "ENDS_WITH",
            "CONTAINS",
            "HAS_SOME",
            "HAS_ALL",
            "EXISTS",
            "URLIZED",
          ],
        },
        encrypted: false,
        plugins: [],
      },
      {
        key: "icon",
        displayName: "Icon",
        type: "REFERENCE",
        typeMetadata: {
          reference: {
            referencedCollectionId: "Icons",
          },
        },
        systemField: false,
        capabilities: {
          sortable: true,
          queryOperators: [
            "EQ",
            "LT",
            "GT",
            "NE",
            "LTE",
            "GTE",
            "STARTS_WITH",
            "ENDS_WITH",
            "CONTAINS",
            "HAS_SOME",
            "HAS_ALL",
            "EXISTS",
            "URLIZED",
          ],
        },
        encrypted: false,
        plugins: [],
      },
      {
        key: "geoJson",
        displayName: "GeoJson",
        type: "REFERENCE",
        typeMetadata: {
          reference: {
            referencedCollectionId: "GeoJson",
          },
        },
        systemField: false,
        capabilities: {
          sortable: true,
          queryOperators: [
            "EQ",
            "LT",
            "GT",
            "NE",
            "LTE",
            "GTE",
            "STARTS_WITH",
            "ENDS_WITH",
            "CONTAINS",
            "HAS_SOME",
            "HAS_ALL",
            "EXISTS",
            "URLIZED",
          ],
        },
        encrypted: false,
        plugins: [],
      },
      {
        key: "popupTitle",
        displayName: "popupTitle",
        type: "TEXT",
        systemField: false,
        capabilities: {
          sortable: true,
          queryOperators: [
            "EQ",
            "LT",
            "GT",
            "NE",
            "LTE",
            "GTE",
            "STARTS_WITH",
            "ENDS_WITH",
            "CONTAINS",
            "HAS_SOME",
            "HAS_ALL",
            "EXISTS",
            "URLIZED",
          ],
        },
        encrypted: false,
        plugins: [],
      },
      {
        key: "popupConent",
        displayName: "PopupConent",
        type: "RICH_CONTENT",
        systemField: false,
        capabilities: {
          sortable: true,
          queryOperators: [
            "EQ",
            "LT",
            "GT",
            "NE",
            "LTE",
            "GTE",
            "STARTS_WITH",
            "ENDS_WITH",
            "CONTAINS",
            "HAS_SOME",
            "HAS_ALL",
            "EXISTS",
            "URLIZED",
          ],
        },
        encrypted: false,
        plugins: [],
      },
    ],
    permissions: {
      insert: "ADMIN",
      update: "ADMIN",
      remove: "ADMIN",
      read: "ANYONE",
    },
    plugins: [
      {
        type: "EDITABLE_PAGE_LINK",
        editablePageLinkOptions: {
          isPersisted: true,
          isMutable: false,
        },
      },
    ],
  },
];
